/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 game.gltf --transform 
Files: game.gltf [3.76KB] > /Users/mainserver/Desktop/3D Models/gamecube_logo/game-transformed.glb [2.18KB] (42%)
Author: Sir2Yas (https://sketchfab.com/yas2yas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gamecube-logo-5f0d3d1077ce44e2bffbe150f5cec3d5
Title: GameCube Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GameModel(props) {
  const { nodes, materials } = useGLTF('/game-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 9.9, 0, 0]}  scale={0.172} />
    </group>
  )
}

useGLTF.preload('/game-transformed.glb')
